# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170830_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('service_desc', models.CharField(max_length=4000)),
                ('service_price', models.PositiveIntegerField()),
            ],
        ),
    ]
