# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170829_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
