# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_service_service_statuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=models.TextField(max_length=4000),
        ),
    ]
