# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170831_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_href',
            field=models.CharField(default='#', max_length=20),
        ),
    ]
